# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cha-chat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for cha-chat
pod 'Firebase/Firestore'
pod 'FirebaseFirestoreSwift'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Firebase/Database'
pod 'SDWebImage', '~> 5.0'
pod 'JGProgressHUD'
pod 'MBProgressHUD', '~> 1.2.0'
pod 'Firebase/Analytics'
pod 'Firebase/Messaging'
end
